const name = "NODES";

export const FETCH_SENTRY_NODE_DELEGATES = `${name}/FETCH_SENTRY_NODE_DELEGATES`;
export const FETCH_SENTRY_NODE_DELEGATES_START = `${FETCH_SENTRY_NODE_DELEGATES}/START`;
export const FETCH_SENTRY_NODE_DELEGATES_END = `${FETCH_SENTRY_NODE_DELEGATES}/END`;
export const FETCH_SENTRY_NODE_DELEGATES_FAILURE = `${FETCH_SENTRY_NODE_DELEGATES}/FAILURE`;
export const FETCH_SENTRY_NODE_DELEGATES_SUCCESS = `${FETCH_SENTRY_NODE_DELEGATES}/SUCCESS`;
